[project]
name = "fonts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.14"
dependencies = [
    "fonttools>=4.63.0",
]

[project.scripts]
fonts = "fonts:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
