// Language and font helpers.
//
// Shobhika covers Devanagari + Cyrillic + Latin + the combining acute U+0301 in
// all four faces (Regular 2500 / Bold 2496 / Italic 2500 / Bold Italic 2496
// glyphs). All faces are shipped in fonts/ and picked up with `--font-path fonts`,
// so nothing has to be installed on the build machine. The two italic faces are
// generated by fonts/src/fonts/build-shobhika-family.py (PT Serif italic outlines
// transplanted into Shobhika), which means `style: "italic"` stays inside this one
// family and NO font fallback list is declared anywhere: a missing glyph is a bug,
// not something to paper over.
#let body-font = "Shobhika"

// Marck Script: Cyrillic handwriting, shipped in fonts/. Replaces Wolgast Two.
// Note: no Devanagari and no U+0301 — only ever used on single Cyrillic letters.
#let cursive-font = "Marck Script"

#let ru(body) = text(lang: "ru", font: body-font, body)
#let ruit(body) = text(lang: "ru", font: body-font, style: "italic", body)
#let ruscursive(body) = text(lang: "ru", font: cursive-font, body)

// \sru existed only for PDF-bookmark safety (\texorpdfstring); Typst needs no split.
#let sru = ru
