# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container:
      image: docker.pkg.github.com/pndv/tex-docker/texlive-fedora-docker:1.0
    #      credentials:
    #        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set git configuration
        run: | 
          git config --global user.name pndv
          git config --global user.email ${{ secrets.GH_USER_EMAIL }}
          git config --global pull.rebase true
          git fetch --all


      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # First time there will be errors/warnings related to BibTeX etc.

      # Build BibLaTeX
      - name: Running Biber
        run: biber main

      # Build MakeIndex
      - name: Running MakeIndex
        run: makeindex main

      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # First time there will be errors/warnings related to BibTeX etc.

      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # todo: check why it's failing

  push:
    needs: test
    runs-on: ubuntu-latest
# todo: Put this section in the release part#      - name: Copy the PDF file to 'pages' folder
#        run: cp main.pdf pages
#
#      - name: Commit and push the file
#        run: |
#          git add --force pages/main.pdf
#          git commit -m "Add PDF file"
#          git push
