# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container:
      image: texlive/texlive:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Change working directory to home
        run: cd /home

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Create auxiliary and output directory for LaTeX
      - name: Create aux/out directories
        run: mkdir out

      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # First time there will be errors/warnings related to BibTeX etc.

      #      - name: Print log
#        run: |
#          cat /miktex/.miktex/texmfs/data/miktex/log/xelatex.log
#          cat /miktex/.miktex/texmfs/data/miktex/log/initexmf.log

      # Build BibLaTeX
      - name: Running Biber
        run: biber main

      # Build MakeIndex
      - name: Running MakeIndex
        run: makeindex main

      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # First time there will be errors/warnings related to BibTeX etc.

      # Build LaTeX file
      - name: Running XeLaTeX
        run: xelatex --admin -file-line-error -interaction=nonstopmode -synctex=1 main.tex
        continue-on-error: true # todo: check why it's failing



